export const filterItems = {
    brands: ['Acronym', 'Adidas', 'Clot', 'Comme des Garçons', 'Converse', 'Eric Koston', 'Fear Of God', 'Maison Chateau Rouge',
        'Missing Link', 'Nike', 'Off-White', 'Parra', 'Patta', 'Pharrell', 'Sacai', 'Sean Wotherspoon', 'Serena Williams', 'Supreme',
        'Travis Scott', 'Undercover', 'Union'],
    models: [
        'Adapt Huarache',
        'Air Fear of God 1',
        'Air Fear Of God Raid',
        'Air Force 1 Low',
        'Air Force 1 Low Skeleton',
        'Air Force 1 Utility',
        'Air Jordan 13 Low',
        'Air Jordan 1 Low',
        'Air Jordan 1 Low SB',
        'Air Jordan 1 Mid',
        'Air Jordan 1 Mid SE',
        'Air Jordan 1 Retro High OG',
        'Air Jordan 1 Retro High OG Track Red',
        'Air Jordan 1 Retro High OG Turbo Green',
        'Air Jordan 1 Retro High SB',
        'Air Jordan 1 Retro High Zoom',
        'Air Jordan 6 Retro',
        'Air Jordan 7 Retro',
        'Air Max 1',
        'Air Max 1/97',
        'Air Max 90',
        'Air Max 97 Ultra 17 Skepta',
        'Air Presto',
        'Air Presto Mid',
        'Air VaporMax',
        'Blazer Mid',
        'Chuck 70',
        'Dunk Low',
        'Dunk Low SB',
        'Dunk Low SP Retro',
        'Dunk SB Low',
        'Fragment Design x CLOT x Air Force 1',
        'G-Dragon x Air Force 1 07',
        'Hyperdunk 2017 Flyknit',
        'LDWaffle',
        'Lunar Force 1',
        'NikeCraft Mars Yard Overshoe',
        'NMD Human Race Trail PRD',
        'Parra x Blazer Low',
        'React Element 87',
        'Skepta x Air Max 97 Ultra 17',
        'Skepta x Air Max Deluxe',
        'Soulland x Blazer Mid SB',
        'SpongeBob SquarePants x Kyrie 5 Pineapple House',
        'Travis Scott x Air Force 1',
        'Wmns Air Jordan 1 Retro High',
        'Wmns Air Zoom Terra Kiger 5',
        'Wmns Vapor Street Laser Fuchsia',
        'Wmns Vapor Street Tour Yellow',
        'Yeezy 500',
        'Yeezy 500 High',
        'Yeezy 700 V3',
        'Yeezy Boost 350 V2',
        'Yeezy Boost 350 V2 Infant',
        'Yeezy Boost 380 Alien',
        'Yeezy Boost 700',
        'Yeezy Boost 700 V2',
        'Yeezy Boost 700 Wave Runner',
        'Yeezy Desert Boot',
        'Zoom Fly Mercurial Flyknit',
        'Zoom Fly SP',
        'ZX 4000 Futurecraft 4D Carbon',],
    sizes: [
        '3', '4', '4.5',
        '5', '5.5', '6',
        '6.5', '7', '7.5',
        '8', '8.5', '9',
        '9.5', '10', '10.5',
        '11', '11.5', '12',
        '12.5', '13', '13.5', '14',
        '16'
    ]
}